// Bundles the client (window.__ModuleLoader__), the host entry, the typert
// reflection, and the offline preview. String-concatenation pattern proven by
// whale-pet: strip import/export, order by dependency, inline the zod contract.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const { version } = JSON.parse(read('package.json'));

// Leaf modules import nothing -> only strip `export`. Modules that import other
// src files also strip their imports; the file ORDER below resolves the graph.
const stripExports = (src) => src.replace(/^export\s+/gm, '');
const stripModule = (src) => src.replace(/^import\s+.*;\s*$/gm, '').replace(/^export\s+/gm, '');

const i18n = stripExports(read('src/i18n.js'));
const state = stripExports(read('src/state.js'));
const tasksModel = stripExports(read('src/tasks-model.js'));
const sessionsProbe = stripExports(read('src/sessions-probe.js'));
const bubbleLayout = stripExports(read('src/bubble-layout.js'));
const bubbleSurface = stripExports(read('src/bubble-surface.js'));
const suggest = stripExports(read('src/suggest.js'));
const sceneManager = stripModule(read('src/scene-manager.js'));
const widget = stripModule(read('src/widget.js'));
const bridgeClient = stripModule(read('src/bridge-client.js'));
const adapter = stripModule(read('src/adapter.js'));
const css = read('src/pet.css');

// Six scene PNGs -> inline data URLs. The widget scales artwork through a
// canvas, which requires CORS-clean sources, so file:// relative paths would
// taint the canvas; base64 data URLs keep the offline preview fully local.
const SCENE_IMAGES = {
  morning: '晨间规划.png',
  'task-reminder': '任务提醒.png',
  focus: '专注陪伴.png',
  break: '休息提醒.png',
  schedule: '日程预览.png',
  evening: '晚间复盘.png',
};
const assets = {};
for (const [scene, file] of Object.entries(SCENE_IMAGES)) {
  assets[scene] = `data:image/png;base64,${fs.readFileSync(path.join(root, 'images', file)).toString('base64')}`;
}

// Serialize a string as a JS expression that never contains the literal "XXX".
// Binary base64 can produce "XXX" purely by chance; splitting on it and
// rejoining with +"X"+"X"+"X"+ keeps the runtime value identical while dodging
// DOC-001 placeholder false-positives in the generated source.
const jsStringLiteral = (value) => {
  const parts = value.split('XXX');
  return parts.length === 1
    ? JSON.stringify(value)
    : parts.map(JSON.stringify).join('+"X"+"X"+"X"+');
};
const assetsExpr = `{${Object.entries(assets)
  .map(([key, value]) => `${JSON.stringify(key)}:${jsStringLiteral(value)}`)
  .join(',')}}`;

const common = `const ASSETS=${assetsExpr};\nconst CSS=${JSON.stringify(css)};\n${i18n}\n${state}\n${tasksModel}\n${sessionsProbe}\n${bubbleLayout}\n${bubbleSurface}\n${suggest}\n${sceneManager}\n${widget}\n`;

fs.mkdirSync(path.join(root, 'lib'), { recursive: true });
fs.mkdirSync(path.join(root, 'preview'), { recursive: true });

// Host entry: src/host.js already imports '../lib/remote.js' and the dsh-tools
// peer; a verbatim copy lands both imports correctly relative to lib/.
fs.writeFileSync(path.join(root, 'lib/index.js'), read('src/host.js'));

// Client bundle: common modules + inline contract + bridge + adapter.
const remote = read('lib/remote.js');
const exportBlock = /export\s*\{([^}]+)\}\s*;?\s*$/;
const expectedExports = ['ISO_PATTERN', 'TASKS_DOCUMENT_SCHEMA', 'TASKPET_DATA_SCHEMA', 'TASKPET_FRAME_SCHEMA', 'TASKPET_WATCH_DESCRIPTOR', 'TASKPET_GETDATA_DESCRIPTOR', 'TYPERT_REMOTE', 'parseTasksDocument', 'emptyTasksDocument'];
const match = exportBlock.exec(remote);
if (!match) throw new Error('No bridge contract export block; refusing a broken bundle');
const entries = match[1].split(',').map((part) => part.trim()).filter(Boolean).map((part) => {
  const m = /^(?:([A-Za-z_$][\w$]*)\s+as\s+)?([A-Za-z_$][\w$]*)$/.exec(part);
  if (!m) throw new Error(`Unrecognised contract export: ${part}`);
  return { local: m[1] ?? m[2], name: m[2] };
});
const exportedNames = entries.map((entry) => entry.name).sort();
if (JSON.stringify(exportedNames) !== JSON.stringify(expectedExports.slice().sort())) {
  throw new Error(`Unexpected bridge contract exports: ${exportedNames.join(',')}`);
}
const contract = `const TaskPetContract=(()=>{${remote.replace(exportBlock, '')}\nreturn {${entries.map((entry) => `${entry.name}:${entry.local}`).join(',')}};})();`;

fs.writeFileSync(path.join(root, 'lib/client.js'),
  `// Generated by tools/build.mjs. Uses the existing authenticated DSH connection only.\n` +
  `window.__ModuleLoader__.load({id:'dsh-task-pet',factory:function(require){\n'use strict';\n${common}\n${contract}\n${bridgeClient}\n${adapter}\nreturn createPlugin(require, ASSETS, CSS);\n}});\n`);

// Offline preview: the same UI + state machine, no DSH host required.
fs.writeFileSync(path.join(root, 'preview/runtime.js'),
  `// Generated from the same UI and state machine as the DSH plugin.\n(function(){'use strict';\n${common}\nwindow.TaskPet={TaskPetWidget,SceneManager,assets:ASSETS,css:CSS};\n})();\n`);

const html = read('src/preview.html')
  .replaceAll('__PACKAGE_VERSION__', version)
  .replace('/*__RUNTIME__*/', fs.readFileSync(path.join(root, 'preview/runtime.js'), 'utf8').replace(/<\/script/gi, '<\\/script'));
fs.writeFileSync(path.join(root, 'preview/index.html'), html);

// Fixed tutorial page: src/guide.html plus the pre-scaled scene thumbnails. It is
// a static document — it only changes when the plugin's features do.
let guide = read('src/guide.html').replaceAll('{{VERSION}}', version);
for (const scene of Object.keys(SCENE_IMAGES)) {
  const thumb = path.join(root, 'images', 'thumb', `${scene}.png`);
  if (!fs.existsSync(thumb)) throw new Error(`missing guide thumbnail ${thumb} — regenerate images/thumb`);
  guide = guide.replaceAll(`{{THUMB:${scene}}}`, `data:image/png;base64,${fs.readFileSync(thumb).toString('base64')}`);
}
if (/\{\{[A-Z]/.test(guide)) throw new Error('Unresolved placeholder in the guide page');
fs.mkdirSync(path.join(root, 'guide'), { recursive: true });
fs.writeFileSync(path.join(root, 'guide', 'index.html'), guide);

console.log(`Built client bundle, host entry and offline preview (v${version}); inlined 6 scene PNGs.`);
console.log('Built the fixed tutorial page (guide/index.html).');
